development:
  FACEBOOK_APP_ID: 222770607887849
  FACEBOOK_SECRET: 0fb89e74743324da4678e43ba910153f

test:
  FACEBOOK_APP_ID: 12345
  FACEBOOK_SECRET: abcdef

production:
  FACEBOOK_APP_ID: 1456984557854877
  FACEBOOK_SECRET: b9b32e73e1617b09353ff1c489d7b7c1